server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: ead-auth
          uri: lb://EAD-AUTH
          predicates:
            - Path=/auth/**
        - id: ead-course
          uri: lb://EAD-COURSE
          predicates:
            - Path=/courses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost