server:
  port: 8082
  servlet:
    context-path: /courses

spring:
  application:
      name: ead-course

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead_course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  output:
    ansi:
      enabled: Always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    com.br: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true


ead:
  api:
    url:
      authuser: 'http://ead-auth/auth'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost